-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgak5V/tkBh6D0s+E+
J8t4iFC6+NJT12jTfS4uBedNHWKgCgYIKoZIzj0DAQehRANCAASr7GkUz0BFEHTx
wL/kFp2sNez3ZSBn4/LxH2BJS/raNShfzlu5fmlKBdgl5w/fejjHfK3mwEKGv8jI
XGUOINyb
-----END PRIVATE KEY-----